{{- if .Values.elasticsearch.enabled }}
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "rancher-logging.labels" . | indent 4 }}
spec:
  controlNamespace: {{ .Release.Namespace }}
  fluentbit: {}
  fluentd: {}
{{- end }}
